### ISSUE TITLE
Getting playhead time

### ISSUE THREAD

**Issue by MeestorX** [LykaiosNZ/companion-module-cockos-reaper#1]
I'm trying to add a variable for the current playhead position, which looks to be defined here:
https://github.com/LykaiosNZ/reaper-osc.js/blob/509a7258d80da3895ce42dbd9b674b3fd969bb5e/src/Transport.ts#L36C1-L37C1

but, I cannot add the variable in the companion module. Likely doing something stupid...
It doesn't seem to recognize `'time'`. I tried `'isPlaying'` just to test, and that is working...
```
function VariableDefinitions(): ReaperPropertyVariableDefinition[] {
	const variables: ReaperPropertyVariableDefinition[] = [
		{
			variableId: 'playHeadTime',
			name: 'Playhead Time',
			getProperty: NotifyPropertySelector<Transport>((reaper) => reaper.transport, 'time'),
		}
	]
	return variables
}
```

**Comment by LykaiosNZ** [comment]
If you have the latest commit and ensure you have reaper-osc `0.5.0` installed, you can add it like so:

```js
{
   ...TransportVariable('playHeadTime', 'Playhead Time', 'time'),
   valueConverter: ... // you might want to convert from seconds to a format like hh:mm:ss here
},
```

**Comment by MeestorX** [comment]
So, don't use `getProperty` then?

**Comment by LykaiosNZ** [comment]
`TransportVariable()` is a helper method I made to make setting up individual variables less arduous, it does that under the hood using the third argument which is of type `keyof Transport & string`

It provides all the properties needed for the `ReaperPropertyVariableDefinition` except for the optional `valueConverter`
